# Generated by Django 3.2.23 on 2024-06-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='image',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='price',
        ),
    ]
